apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: coffee-shop-db
spec:
  instances: 2
  postgres:
    version: '15'
  pods:
    persistentVolume:
      size: '5Gi'
  managedSql:
   scripts:
   - sgScript: coffee-shop-script
  prometheusAutobind: true
---

apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: coffee-shop-script
spec:
  scripts:
    - name: schema-init
      script: |
        CREATE TABLE public.coffee_orders (
                                       id uuid NOT NULL,
                                       type character varying(255) NOT NULL
        );
        ALTER TABLE ONLY public.coffee_orders
            ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
---
